/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {},
  },
  // theme is used to customize the default styles of tailwind, we can add our own colors, fonts, spacing, etc. in the theme object and then use those styles in our components by using the class names generated by tailwind based on the theme configuration
  // extend is used to add new styles to the default styles of tailwind, we can add new colors, fonts, spacing, etc. in the extend object and then use those styles in our components by using the class names generated by tailwind based on the theme configuration
  plugins: [],
};