import { createSlice, current } from "@reduxjs/toolkit";
// createSlice is a function provided by Redux Toolkit that simplifies the process of creating a Redux slice, which is a collection of Redux reducer logic and actions for a specific feature or domain of the application. It takes an object as an argument that defines the name of the slice, the initial state, and the reducers that handle different actions. Each reducer is a function that takes the current state and an action as arguments and returns a new state based on the action type. The createSlice function automatically generates action creators and action types based on the reducers defined in the slice, making it easier to manage and organize state logic in a Redux application. Slices help to keep related state and logic together, improving code organization and maintainability.

const cartSlice = createSlice({
// function takes a configuration object with a name property that specifies the name of the slice, this name is used to generate action types and action creators for the slice, it should be unique across the application to avoid conflicts with other slices, in this case we are naming our slice "cart" because it will handle the state and actions related to the shopping cart in our application.
  name: "cart", // name of slice
  initialState: { // initialState is the initial state of the slice, it can be any JavaScript value, but it is usually an object that represents the state of the feature or domain that the slice is responsible for, in this case we are initializing the state with an object that has a single property "items" which is an empty array, this will represent the items in the shopping cart, and we will update this array as items are added or removed from the cart.
    items: [],
  },
  reducers: { // reducers is an object that defines the reducer functions for the slice, each key in the reducers object represents an action type, and the corresponding value is a reducer function that takes the current state and an action as arguments and returns a new state based on the action type, in this case we are defining three reducers: addItem, removeItem, and clearCart, which will handle adding items to the cart, removing items from the cart, and clearing the cart respectively.
    addItem: (state, action) => {
      // Redux Toolkit uses immer BTS
      // immer allows us to write "mutating" logic in our reducers, but it actually creates a new immutable state behind the scenes, so we can write code that looks like we are mutating the state directly, but it is actually creating a new state object with the updated values, this makes it easier to write reducers without worrying about immutability, and it also helps to avoid common mistakes when updating state in Redux.
      state.items.push(action.payload);
    },
    removeItem: (state, action) => {
      state.items.pop();
    },
    //originalState = {items: ["pizza"]}
    clearCart: (state, action) => {
      //RTK - either Mutate the existing  state or return a new State
      // state.items.length = 0; // originalState = []

      return { items: [] }; // this new object will be replaced inside originalState = { items: [] }
    },
  },
});

// cartSlice object will something like this
// cartSlice = {
//   name: "cart",
//   reducer: function that will be used in the Redux store to handle the actions dispatched from our components and update the cart state accordingly,
//   actions: {
//     addItem: function that returns an action object with a type property that corresponds to the reducer function defined in the slice, and a payload property that contains the data needed to update the state,
//     removeItem: function that returns an action object with a type property that corresponds to the reducer function defined in the slice, and a payload property that contains the data needed to update the state,
//     clearCart: function that returns an action object with a type property that corresponds to the reducer function defined in the slice, and a payload property that contains the data needed to update the state,
//   }
// }    

export const { addItem, removeItem, clearCart } = cartSlice.actions; // exporting the action creators generated by createSlice, these action creators are functions that return an action object with a type property that corresponds to the reducer function defined in the slice, and a payload property that contains the data needed to update the state, in this case we are exporting the addItem, removeItem, and clearCart action creators so that they can be used in our components to dispatch actions to the Redux store and update the cart state accordingly.

export default cartSlice.reducer; // exporting the reducer function generated by createSlice, this reducer function will be used in the Redux store to handle the actions dispatched from our components and update the cart state accordingly, it will take the current state and an action as arguments and return a new state based on the action type defined in the reducers object of the slice, in this case it will handle the addItem, removeItem, and clearCart actions to update the items array in the cart state. The reducer function will be used in the Redux store to manage the state of the cart in our application, allowing us to add items to the cart, remove items from the cart, and clear the cart as needed based on user interactions in our components.